creation_rules:
  - path_regex: (secrets/)?prod\.enc\.ya?ml$
    # `terraform -chdir=infra/bootstrap output kms_key_arn` の値に置き換える
    kms: arn:aws:kms:ap-northeast-1:767397787931:key/eff89739-fdd6-496e-a105-89032a31d95a
