vercel_api_token: ENC[AES256_GCM,data:Mz4u95pD9tWDELIVFA4jwbNjMyi/diNidJL9Q+heIGSBNQKrozOawbG4tLXmnOnn4NamK7qv8u/cfiQv,iv:kaJjg8lvHJpFhM3eA5r+KaQcycLo+y3MK//wfcebDc0=,tag:QQN4hspn3iRuVEpJuUEGfw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:767397787931:key/eff89739-fdd6-496e-a105-89032a31d95a
          aws_profile: ""
          created_at: "2026-07-20T13:46:56Z"
          enc: AQICAHjcTWYDQ7bl3xqdj1lPqwC4gtB9wzBmfXDlPCMpwzfBfAETniszEgiwq3o/cAZy3bOtAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnsblV7Z7yeujUcJsAgEQgDvzLj3s77K0yu+nmgaynASQqfaY8AOxk3g5H/Fzx4pNSNNKsnmIq1VEFaLEyTrRinHX3ad5B30NqRA9WA==
    lastmodified: "2026-07-20T13:48:02Z"
    mac: ENC[AES256_GCM,data:CPY+P5PLTvQART7VUV69aqt7u/jOEjVlWYKg6CWPhCM0fhkDb6RUVdmI3JWNRfcxJq4JxpAyZaQ8FdCYg3L/ynaAi6HKm0DqHl30dY38OVm4RCOKFi2LNP5/XXleYBMWzKNSxWHCNRiXof6qk/WEMw1Cd0uZFr6TwL61XC0PkAc=,iv:7ypNwXRZnaOQACJwCzeufN5HGZNGaIeq1iN+QZ5k21o=,tag:HoKw0/OGxzLsI8VWA2g7PQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
